language: node_js

install:
- npm install

matrix:
  fast_finish: true
  include:
    - node_js: 8
      env: TYPE=UNIT_CODESTYLE_DEPENDENCY
      script:
      - npm run test:unit
      - npm run lint
      - npm run check

notifications:
  slack:
    rooms:
      secure: ZMe+oIZ41Hd09SJ8GjC+eWszZhLj6TDKXnmgYF7wSY59te8/leTqMaRSs1DbRaB+8IqaRViPV91FfwMZyRlyMyCxXQvZalFXLxirKEr/nW+ThnyXDtpoyialhVs/ra3hgPo6GGsLVWXMg01raZypPqplf+Lz9lp5HmYVXSLPLuxBipK4A+XH9IMeYLJbRzIzP0TwaWP2k946n2rpjT20JC42MDpMwWClZDT60kYwFxdOOtDcfpQ1UfIGDNAtOMa8tVrE9Z2OzUbqMxthS6AEqsZIr0b5TmindYkxzw+Pps+lJYjFAOZIW1FrwxHEOFcO4cU/Pa4cB5UMP/HPZWYTvVnwI/FSFAvsWPM69Qzz2sT9BqJxQGRNB1hcsyy3Vr7Onn4ip7worinGj5xMaFRwAKJx3BT/xC/a5WZjtH9QY7QuDy4yLNn9W/NYA2Ee5fveoFHZYPEaxQ5lCXb+kQtQ6rgwWkeQKqp5XEPcpBB8YKGfy5cakGPBdPSBJIDwDvER1MGSXVfYBVMo3/t6HYQn7HODKLPWGUBpLxl421xlb4btorF6DzrWMwiFUa+LJ+bdgX4XrHYzjs13veRO22XQ2J3lTYRWS3utuwWv0F4hBNeDN8etSOW+bxPtdz2H5aUqOTIR6GCveNxL2RiKIXQIiZFqT6f6wuR76XLZl+xP5Go=
    on_success: change
    on_failure: always
